### ISSUE TITLE
Error in Readme

### ISSUE THREAD

**Issue by aerickso** [jopo666/HistoEncoder#1]
Hi!

Thank you for providing HistoEncoder to the community. I ran into an issue with your readme on a Window 64-bit operating system running Windows 11 Home. 

```
HistoPrep --input 'my/local/directory/slide_images/*.jpg' --output ./tile_images --width 512 --overlap 0.5 --max-background 0.5
ERROR: Found no files matching pattern 'my/local/directory/slide_images/*.jpg''.
```

Fixed by changing to:

`HistoPrep --input "my/local/directory/slide_images/*.jpg" --output ./tile_images --width 512 --overlap 0.5 --max-background 0.5
`

**Comment by jopo666** [comment]
Fixed by 989e214
